import { StyleSheet } from 'react-native';
import { RFValue } from 'react-native-responsive-fontsize';

export default StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: RFValue(80),
    backgroundColor: '#00bcd4',
    //backgroundColor: '#1f1f1f',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  titleContainer: {
    marginBottom: 20,
  },
  titleText: {
    fontWeight: 'bold',
    fontSize: 35,
    color: '#00001F',
  },
  infoFields: {
    width: '100%',
    backgroundColor: '#ffffff',
    borderRadius: 10,
    padding: 20,
    alignItems: 'center',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    minHeight: 265,
  },
  input: {
    width: '100%',
    padding: 15,
    marginVertical: 10,
    backgroundColor: '#fff',
    borderRadius: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 2,
    elevation: 5,
    borderRadius: 10,
  },
  button: {
    width: '100%',
    height: 50,
    backgroundColor: '#007bff',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
    marginTop: 10,
  },
  buttonText: {
    color: '#ffffff',
    fontSize: RFValue(16),
    fontWeight: 'bold',
  },
  logo: {
    width: 100,
    height: 100,
    marginBottom: 30,
  },
  appName: {
    fontSize: 35,
    color: '#00001F',
  },
  registerButton: {
    marginTop: 20,
    backgroundColor: '#007BFF',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 5,
  },
  registerButtonText: {
    color: '#fff',
    fontSize: 18,
    textAlign: 'center',
  },
  registerTitle: {
    width: RFValue(250),
    height: RFValue(60),
    marginBottom: 30,
  },
  errorMessageText: {
    marginTop: 10,
    fontSize: 16,
    color: '#e62532',
    textAlign: 'center',
  },
  scrollContainer: {
    flex: 1, 
    flexDirection: 'column',
    justifyContent: 'center',
    flexGrow: 1,
    backgroundColor: '#00bcd4',
  },
});
